services:
  # FastAPI backend
  - type: web
    name: dsa-backend-rag
    runtime: python
    plan: free
    buildCommand: pip install -r Backend/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker Backend.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: Embedding_URL
        sync: false
      - key: LLM_URL
        sync: false
    healthCheckPath: /

  # Django frontend
  - type: web
    name: dsa-frontend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DSA_BACKEND_START_URL
        value: ${dsa-backend-rag.url}/start
      - key: ALLOWED_HOSTS
        value: ${dsa-frontend.url}
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
    healthCheckPath: /
